name: Docker Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push: #equivalent to job in ADO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6 #equivalent to task in ADO
      - name: Log in to the Container registry #displayName in ADO
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: | #equivalent to script:
          docker build . --tag ghcr.io/akmal-esteem321/skills-publish-docker-images/stackoverflown:main
          docker push ghcr.io/akmal-esteem321/skills-publish-docker-images/stackoverflown:main